mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/utils/*Mapper.xml
  # 如果是放在resource目录 classpath:/utils/*Mapper.xml
  #  utils-locations: classpath*:com/myzone/**/**.xml,classpath*:mapping/**/**.xml
  mapper-locations: classpath:/utils/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.myzone.**.entity,com.myzone.**.dto
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 0:"忽略判断"--IGNORED,1:"非 NULL 判断"--NOT_NULL,2:"非空判断"--NOT_EMPTY
#      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
      #      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: mysql