server:
  port: 8081

#spring:
#  security:
#    user:
#      name: java
#      password: 123456

#thymeleaf
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html